### ISSUE TITLE
Beats dashboard not available

### ISSUE THREAD

**Issue by urosj** [juju-solutions/bundle-beats-core#4] opened 2016-08-05 10:59 UTC
Tried, but still seeing error in Kibana:  No default index pattern. You must select or create one to continue.

@chuckbutler did I miss a step?

urulama@ubuntu:~/github$ juju run-action kibana/0 load-dashboard dasboard=beats
Action queued with id: a2a97da7-eb34-4554-82b4-dd1a45303bbc
urulama@ubuntu:~/github$ juju status
MODEL    CONTROLLER  CLOUD/REGION   VERSION
default  lokalc      lxd/localhost  2.0-beta15.1

APP             VERSION  STATUS   EXPOSED  ORIGIN      CHARM           REV  OS
xxx           active   true     local       xxx  1    ubuntu
yyy               unknown  true     local      yyy      1    ubuntu
elasticsearch            unknown  false    jujucharms  elasticsearch   15   ubuntu
filebeat                          false    jujucharms  filebeat        2    ubuntu
kibana                   active   true     jujucharms  kibana          12   ubuntu
mongodb                  unknown  false    jujucharms  mongodb         37   ubuntu
topbeat                           false    jujucharms  topbeat         2    ubuntu

RELATION       PROVIDES        CONSUMES       TYPE
xxx      xxx  yyy     regular
beats-host    xxx  filebeat       subordinate
database      xxx  mongodb        regular
client         yyy      elasticsearch  regular
beats-host     yyy      filebeat       subordinate
database       yyy      mongodb        regular
peer           elasticsearch   elasticsearch  peer
elasticsearch  elasticsearch   filebeat       regular
rest           elasticsearch   kibana         regular
elasticsearch  elasticsearch   topbeat        regular
replica-set    mongodb         mongodb        peer

UNIT              WORKLOAD  AGENT  MACHINE  PUBLIC-ADDRESS   PORTS                                    MESSAGE
xxx/0  active    idle   3        192.168.122.151  8081/tcp                                 wrote configuration
  filebeat/1      active    idle            192.168.122.151                                           Filebeat ready
yyy/0      unknown   idle   0        192.168.122.108  8080/tcp  
  filebeat/0      active    idle            192.168.122.108                                           Filebeat ready
elasticsearch/0   unknown   idle   2        192.168.122.220  9200/tcp  
kibana/0          active    idle   4        192.168.122.32   80/tcp,9200/tcp                          ready
mongodb/0         unknown   idle   1        192.168.122.163  27017/tcp,27019/tcp,27021/tcp,28017/tcp  

MACHINE  STATE    DNS              INS-ID         SERIES  AZ
0        started  192.168.122.108  juju-4d6878-0  trusty  
1        started  192.168.122.163  juju-4d6878-1  trusty  
2        started  192.168.122.220  juju-4d6878-2  trusty  
3        started  192.168.122.151  juju-4d6878-3  trusty  
4        started  192.168.122.32   juju-4d6878-4  trusty

**Comment by urosj** [comment] 2016-08-05 14:00
Updated the index to be built from filebeat-\* but the dashboard is still not installed with the action.

**Comment by lazypower** [comment] 2016-08-05 15:12
@urosj - the index pattern is still a manual step. I need to get a curl operation or something in there, however I feel like it's a preference to set default context when you log in.

is the deployment still active? I'd like to get some probing questions answered about the state you're left in. It's now deployable via config, as well as an action. I may need to update the README

**Comment by lazypower** [comment] 2016-08-05 16:25
Per our conversation on irc/hangouts - the issue is due to the new behavior that landed modifying the action to work as both config, and an action. This leads me to believe we have no test coverage around this particular feature, and that should be corrected.

The temporary work-around to this is to set the dashboard as config,  eg:

```
juju set-config kibana dashboards="beats"
```

I'll get a fix published however to both the readme, the action code, and have something up for you to test post haste.

**Comment by kwmonroe** [comment] 2019-10-01 18:57
This is fixed.  When kibana is configured with `dashboards=beats`, you should be able to set the filebeat index as the default, then the "Discover" tab in the kibana UI shows the data.

**Closed as completed by kwmonroe** 2019-10-01 18:57 UTC
Labels: bug
